### ISSUE TITLE
Project code #1

### ISSUE THREAD

**Issue by xp1632** [vordemann/relevance-detection-etra2020#2]
Hello Lukas,

I am really inspired by the proposed voting metrics in the paper, and would like to generalize the idea to the reading scenario.
Would you mind sharing the dataset and code?

Thank you very much!

Ziwei He

**Comment by vordemann** [comment]
Hi Ziwei He,

thank you for the reminder. 
I will clean up the code this upcoming week and upload it here. 
Regarding the dataset, I need to check first if I am allowed to share it here as well.

All the best,
Lukas

**Comment by xp1632** [comment]
Thank you very much! Looking forward to it!
